### ISSUE TITLE
brew cask support?

### ISSUE THREAD

**Issue by y-nk** [chamburr/glance#18]
it'd be super nice to have brew cask support for this awesome app

https://github.com/Homebrew/homebrew-cask

**Comment by cbserra** [comment]
It actually already exists from the original repo:

https://github.com/Homebrew/homebrew-cask/blob/master/Casks/glance.rb

Not sure if a new entry should be created, or just overwrite this file. Probably should use a new entry since file paths / package names have changed which would interfere with the `brew`'s `zap` uninstaller, I believe.

**Comment by chamburr** [comment]
Thank you!
