### ISSUE TITLE
Unable to use it in Catalina (macOS 10.15.7)

### ISSUE THREAD

**Issue by dserodio** [chamburr/glance#4]
### Environment

- **App version?** 1.3.1
- **macOS version?** 10.15.7 

### Bug Information

- **What are you trying to do?** Launch Glance for the 1st time
- **What's the expected behavior?**
- **What's the actual behavior?** I get an error:

![image](https://user-images.githubusercontent.com/233589/123116680-7eb41700-d417-11eb-824f-93e9640cc56d.png)

**Comment by chamburr** [comment]
Hi there, I'm unsure about the compatibility with Catalina. You could change the minimum macOS version in Info.plist and code sign it to test, and if it works I could make a new release to fix that. Otherwise, you should use the original Glance app available [here](https://github.com/samuelmeuli/glance/releases).
